format = '''
$os$directory$git_branch$git_status
$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700'
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[os]
disabled = false
format = "[$symbol](color8) "

[os.symbols]
Arch = " "

[character]
success_symbol = "[❯](color8 bold) "
error_symbol = "[❯](bold #f38ba8) "
vicmd_symbol = "[❮](color9 bold) "

[directory]
format = "[󰉋 ](color1)[$path](color3 bold) "

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "
".config" = " 󰒓 "
"scripts" = "󱆃 "  
"vault" = "󰌾 "

[git_branch]
symbol = " "
format = "on [$symbol$branch](color8) "

[git_status]
format = '([\[$all_status$ahead_behind\]](color3) )'
stashed = "≡"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
renamed = "»"
deleted = "✘"
modified = "!"
staged = "+"
untracked = "?"
conflicted = "="
