
windowrulev2 = tile, initialClass:^(Godot)$, initialTitle:^(Godot)$

windowrulev2 = float, title:^.*(\(DEBUG\))$
windowrulev2 = center, title:^.*(\(DEBUG\))$
windowrulev2 = size 1920 1080, title:^.*(\(DEBUG\))$
