windowrule {
  name = Godot-tile
  tile = on
  match:class = ^(Godot)$
  match:title = ^(Godot)$
}

windowrule {
  name = debug-centered
  float = on
  center = on
  size = 1920 1080
  match:title = ^.*(\(DEBUG\))$
  match:initial_title = ^(Godot)$
}
