source=./defaults.conf
source=./keybinds.conf
source=./lookandfeel.conf
source=./input.conf
#Specific apps configuration
source=./apps/app.conf

# Monitors are not included and need to be changed, everyone has a diferent monitor after all
# Define your file, the monitor file is in .gitignore so you need to make one
# Or just decomment this:
# monitor = , preferred, auto, 1

source=./monitor.conf

exec-once=$bar
exec-once=waypaper --restore
exec-once=hypridle
exec-once=swaync

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that
